version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    groups:
      quarkus:
        patterns: ["io.quarkus*"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: "/src/main/docker"
    schedule:
      interval: monthly