# Application
%dev.library.max-loans=10
%dev.quarkus.http.host=127.0.0.1
quarkus.rest-client.open-library.url=https://openlibrary.org

# Database
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.datasource.db-version=16
%dev.quarkus.hibernate-orm.sql-load-script=import.sql
%test.quarkus.hibernate-orm.sql-load-script=no-file

# OpenAPI
quarkus.smallrye-openapi.info-title=Library API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API de gestion de la bibliothèque
quarkus.smallrye-openapi.info-contact-email=contact@library.com

# JWT
%prod.mp.jwt.verify.publickey.location=publicKey.pem
%dev.mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://example.com/issuer